create extension if not exists vector with schema extensions;

-- Destructive first-time reset: removes only this app's two known tables and their rows.
drop function if exists public.match_documents(extensions.vector, float, integer);
drop table if exists public.documents;
drop table if exists public.clients;

create table if not exists public.clients (
    id bigint generated by default as identity primary key,
    name text not null unique,
    status text not null,
    balance numeric(12, 2) not null default 0,
    email text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.documents (
    id bigint generated by default as identity primary key,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    embedding extensions.vector(384) not null,
    source text not null,
    page integer,
    chunk_index integer not null,
    content_hash text not null,
    created_at timestamptz not null default now(),
    unique (source, chunk_index)
);

create index if not exists documents_embedding_hnsw_idx
    on public.documents using hnsw (embedding extensions.vector_cosine_ops);
create index if not exists documents_source_idx on public.documents (source);

create or replace function public.match_documents(
    query_embedding extensions.vector(384),
    match_threshold float default 0.25,
    match_count integer default 5
)
returns table (
    id bigint,
    content text,
    metadata jsonb,
    source text,
    page integer,
    similarity float
)
language sql
stable
set search_path = public, extensions
as $$
    select d.id,
           d.content,
           d.metadata,
           d.source,
           d.page,
           1 - (d.embedding <=> query_embedding) as similarity
    from public.documents as d
    where 1 - (d.embedding <=> query_embedding) >= match_threshold
    order by d.embedding <=> query_embedding
    limit greatest(1, least(match_count, 20));
$$;

grant select, insert, update, delete on public.clients, public.documents to service_role;
grant usage, select on all sequences in schema public to service_role;
grant execute on function public.match_documents(extensions.vector, float, integer) to service_role;

insert into public.clients (name, status, balance, email)
values
    ('Acme Corp', 'Active', 5000, 'contact@acmecorp.com'),
    ('Globex', 'Pending', 1500, 'billing@globex.com'),
    ('Soylent', 'Overdue', 12000, 'accounts@soylent.com')
on conflict (name) do update
set status = excluded.status,
    balance = excluded.balance,
    email = excluded.email;
